### PR TITLE
Adds Open Graph #38

### PR DESCRIPTION
**Pull request by GabLeRoux**
I followed the following nice article:  
http://davidensinger.com/2013/04/adding-open-graph-tags-to-jekyll/

Generated picture based on website header page and took a look at  
https://developers.facebook.com/docs/sharing/best-practices/

> Image Sizes
> Use images that are at least 1200 x 630 pixels for the best display on high resolution devices. At the minimum, you should use images that are 600 x 315 pixels to display link page posts with larger images. Images can be up to 8MB in size.

So I did the `1200*2` x `630*2` pixels ;)

I updated a few things compared to article's open graph, but it looks good to me. I'll give a try to facebook open graph debugger and see what we get.

- [x] Test with [facebook debugger](https://developers.facebook.com/tools/debug/) using proxy
- [x] Confirm page title is properly passed
- [x] Fix required `Missing Properties The following required properties are missing: fb:app_id`

https://stackoverflow.com/questions/8569892/how-to-test-open-graph-on-localhost

* <del>[ngrok](https://ngrok.com/)</del> doesn't work with facebook open graph debugger.
* <del>[proxylocal](https://github.com/proxylocal/proxylocal-gem)</del> service is shutdown
* [localtunel](https://localtunnel.github.io/www/) ✅ [Answered here](https://stackoverflow.com/a/46816051/1092815) 🎉

### CODE REVIEW

**Comment by GabLeRoux** [comment]
Still one thing to solve:

> Missing Properties The following required properties are missing: fb:app_id

🎉 

image

**Comment by jipiboily** [comment]
Want me to create an app?

JP Boily

Founder @ Metrics Watch 
( https://metricswatch.com/?utm_source=email&utm_medium=gmail-signature )
 (and a new SaaS, see below) - Email Reports & Real-time Alerts
for Google Analytics

On October 18, 2017 at 1:38 PM, Gabriel Le Breton
(notifications@github.com) wrote:

Still a few things to solve:

image 
( https://user-images.githubusercontent.com/1264761/31733430-998841be-b409-11e7-82ab-2aeb3636cf27.png )


—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub 
( https://github.com/saglacio/saglac.io/pull/113#issuecomment-337669628 )
, or mute the thread

**Comment by GabLeRoux** [comment]
Sure, go on 🍻, you can add me and Emile as admins to the app as well 👍

**Comment by emileber** [comment]
We also change the title of the homepage as it says _"Accueil"_ in the shared link preview.

**Comment by jipiboily** [comment]
I'll do that tonight. If you prefer to do it before then, add me
as an admin too plz :)

JP Boily

Founder @ Metrics Watch 
( https://metricswatch.com/?utm_source=email&utm_medium=gmail-signature )
 (and a new SaaS, see below) - Email Reports & Real-time Alerts
for Google Analytics

On October 18, 2017 at 1:43 PM, Gabriel Le Breton
(notifications@github.com) wrote:

Sure, go on 🍻, you can add me and emile as admins to the app as
well 👍

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub 
( https://github.com/saglacio/saglac.io/pull/113#issuecomment-337671222 )
, or mute the thread

**Comment by GabLeRoux** [comment]
I’ll wait ;)

**Comment by jipiboily** [comment]
Didn't forget you. I just didn't have time yesterday, got back
home late, then I've gone to sleep almost immediately. I'll get
it to you in the next few days.

JP Boily

Founder @ Metrics Watch 
( https://metricswatch.com/?utm_source=email&utm_medium=gmail-signature )
 (and a new SaaS, see below) - Email Reports & Real-time Alerts
for Google Analytics

On October 18, 2017 at 1:59 PM, Gabriel Le Breton
(notifications@github.com) wrote:

I’ll wait ;)

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub 
( https://github.com/saglacio/saglac.io/pull/113#issuecomment-337676121 )
, or mute the thread

**Comment by GabLeRoux** [comment]
No stress, same on my side 🛌

**Comment by emileber** [comment]
This fixes #38.

**Comment by jipiboily** [comment]
Pour ça, on a deux options:
- une page Facebook
- une app Facebook

Je crois avoir vu une conversation à propos d'une page...je rêve?

**Comment by emileber** [comment]
@jipiboily effectivement, une page serait le best puisque c'était déjà une option que j'aimerais explorer.

**Comment by emileber** [comment]
Il faudrait updater les liens vers le groupe facebook avec la Page facebook, ou peut-être mettre les deux. Ou ajouter un bouton like... Whatever.

**Comment by jipiboily** [comment]
On a une page FB maintenant! Le app ID, je crois: 130024877754864

**Comment by GabLeRoux** [comment]
Ça va me prendre plus de conviction que ça. Selon https://stackoverflow.com/questions/10339192/how-to-get-app-id-for-an-existing-facebook-page tu peux visiter la page suivante en tant qu'admin:

https://graph.facebook.com/saglacio

Si non, ça prend une app créée ici:
https://developers.facebook.com/apps/

🚀

**Comment by jipiboily** [comment]
C'est outdated ce truc buddy :)

Check https://facebook.com/130024877754864 tu vas être redirigé...95% certain que c'est le bon truc.

**Comment by GabLeRoux** [comment]
Page id = app id?

**Comment by jipiboily** [comment]
Yup!

**Review by emileber — APPROVED** [review]

**Pull request merged**
